import { Schema, Table, column } from '@powersync/common';

export const AppSchema = new Schema({
  trips: new Table({
    name: column.text,
    start_date: column.text,
    destination: column.text,
    destination_city: column.text,
  }),
  pax: new Table({
    user_id: column.text,
    primary_id: column.text,
    trip_id: column.text,
  }),
  itinerary: new Table({
    trip_id: column.text,
    place_name: column.text,
    start_time: column.text,
    duration_mins: column.integer,
    status: column.text,
    entry_fee_type: column.text,
    entry_fee_amount: column.integer,
    day_note: column.text,
  }),
  vehicles: new Table({
    trip_id: column.text,
    transport_type: column.text,
    trip_day: column.integer,
    leg_order: column.integer,
    departure_place: column.text,
    arrival_place: column.text,
    departure_time: column.text,
    arrival_time: column.text,
    driver_name: column.text,
    driver_phone: column.text,
    vehicle_number: column.text,
    airline_name: column.text,
    flight_number: column.text,
    terminal: column.text,
    gate: column.text,
    train_number: column.text,
    train_name: column.text,
    coach: column.text,
    berth_type: column.text,
    cab_company: column.text,
    cab_type: column.text,
    cab_number: column.text,
    cab_driver_name: column.text,
    cab_driver_phone: column.text,
    plate_number: column.text,
  }),
  pax_vehicles: new Table({
    pax_id: column.text,
    vehicle_id: column.text,
    pnr_number: column.text,
    seat_number: column.text,
    ticket_number: column.text,
    berth_number: column.text,
    meal_preference: column.text,
    cab_sharing: column.integer,
  }),
  attendance: new Table({
    pax_id: column.text,
    vehicle_id: column.text,
    checked_in_at: column.text,
    status: column.text,
    via_rep: column.integer,
  }),
  hotels: new Table({
    trip_id: column.text,
    name: column.text,
    address: column.text,
    phone: column.text,
    image_url: column.text,
    stars: column.integer,
    check_in_day: column.integer,
    check_out_day: column.integer,
    check_in_time: column.text,
    check_out_time: column.text,
  }),
  hotel_rooms: new Table({
    hotel_id: column.text,
    room_number: column.text,
    room_type: column.text,
    floor: column.integer,
  }),
  pax_rooms: new Table({
    pax_id: column.text,
    room_id: column.text,
    hotel_id: column.text,
    room_number: column.text,
  }),
  hotel_checkins: new Table({
    pax_id: column.text,
    hotel_id: column.text,
    checked_in_at: column.text,
    status: column.text,
  }),
  notifications: new Table({
    trip_id: column.text,
    title: column.text,
    message: column.text,
    created_at: column.text,
    type: column.text,
  }),
  notif_receipts: new Table({
    notif_id: column.text,
    pax_id: column.text,
    read_at: column.text,
  }),
  users: new Table({
    name: column.text,
    mobile: column.text,
    role: column.text,
    onboarding_complete: column.integer,
  }),
});
